# Registration page locators
LOGIN_OR_REGISTER_BTN = "//a[text()='Login or register']"
CONTINUE_BTN = "//button[@title='Continue']"
FIRSTNAME_INPUT = "id=AccountFrm_firstname"
LASTNAME_INPUT = "id=AccountFrm_lastname"
EMAIL_INPUT = "id=AccountFrm_email"
ADDRESS_INPUT = "id=AccountFrm_address_1"
CITY_INPUT = "id=AccountFrm_city"
REGION_SELECT = "id=AccountFrm_zone_id"
ZIP_INPUT = "id=AccountFrm_postcode"
COUNTRY_SELECT = "id=AccountFrm_country_id"
LOGIN_NAME_INPUT = "id=AccountFrm_loginname"
PASSWORD_INPUT = "id=AccountFrm_password"
CONFIRM_INPUT = "id=AccountFrm_confirm"
PRIVACY_CHECKBOX = "id=AccountFrm_agree"
CONTINUE_SUBMIT = "//button[@title='Continue']"
